// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leuyijcvhifyopdelnxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxldXlpamN2aGlmeW9wZGVsbnh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDEzMTksImV4cCI6MjA2NjQxNzMxOX0.SghS1GekbqxS_M_oMGumHSmnH1AdJSGamshr65-mMno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});